addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.14.9")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.5.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-gzip"                 % "1.0.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"               % "1.1.3")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.0.1")
