addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.14.9")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.5.1")
addSbtPlugin("com.typesafe.play"  % "sbt-plugin"               % "2.7.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.26")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.0.8-0.6")
addSbtPlugin("com.typesafe.sbt"   % "sbt-gzip"                 % "1.0.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"               % "1.1.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
